trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install --prefix ./src/Ocelot.ConfigEditor
  displayName: 'npm install'

- task: CmdLine@2
  inputs:
    script: '.\build.sh'
    failOnStderr: true

