trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install --prefix ./src/Ocelot.ConfigEditor
  displayName: 'npm install'

- task: Cake@0
  inputs:
    script: 'build.cake'
    target: 'Default'
    verbosity: 'Verbose'